### ISSUE TITLE
Re-implementation result

### ISSUE THREAD

**Issue by NeoAlice** [yuyanislearning/CTRL-PG#3]
micro-f1=0.6119
I directly run your code without any change. Is there anything wrong about hyperparameter?

**Comment by yuyanislearning** [comment]
Unfortunately, the code available on github does not include the part of global inference. This is because part of the code is from temporal relation evaluation from i2b2 clinical challenge, which is not allowed to distributed publicly. Please find more detail of the code in the following reference: 
Sun W, Rumshisky A, Uzuner O. J Am Med Inform Assoc 2013;20:806–813.
